import { User } from 'src/users/models/user.entity';
import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';

export type DevicePlatform = 'ios' | 'android' | 'web';
export type PushProvider = 'apns' | 'fcm' | 'webpush' | 'none';

@Entity('devices')
@Index(['user', 'revokedAt', 'lastSeenAt'])
@Index(['user', 'appInstanceId'], { unique: true }) // dedupe per user
export class Device {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE', eager: true })
  user: User;

  // Stable random ID generated by the app on first launch and
  // kept in secure storage.
  @Column({ type: 'uuid' })
  appInstanceId: string;

  @Column({ type: 'varchar', length: 16 })
  platform: DevicePlatform;

  @Column({ type: 'varchar', length: 16, default: 'none' })
  pushProvider: PushProvider;

  // APNS/FCM token, or WebPush endpoint token if we keep it simple
  @Column({ type: 'text', nullable: true })
  pushToken?: string | null;

  // for real WebPush, store full subscription
  @Column({ type: 'text', nullable: true })
  webpushEndpoint?: string | null;
  @Column({ type: 'text', nullable: true })
  webpushP256dh?: string | null;
  @Column({ type: 'text', nullable: true })
  webpushAuth?: string | null;

  @Column({ type: 'text', nullable: true }) locale?: string | null;
  @Column({ type: 'text', nullable: true }) timezone?: string | null;
  @Column({ type: 'text', nullable: true }) model?: string | null;
  @Column({ type: 'text', nullable: true }) osVersion?: string | null;
  @Column({ type: 'text', nullable: true }) appVersion?: string | null;

  @Column({ type: 'timestamptz', nullable: true }) lastSeenAt?: Date | null;
  @Column({ type: 'timestamptz', nullable: true }) revokeAt?: Date | null;

  @CreateDateColumn() createdAt: Date;
  @CreateDateColumn() updatedAt: Date;
}
